const typePrefix = 'RESERVATIONS:APP';

export const TYPES = {
  FETCH_RESERVATIONS_LIST_SUCCESS: `${typePrefix}:FETCH_RESERVATIONS_LIST_SUCCESS`,
  FETCH_RESERVATIONS_LIST_FAILURE: `${typePrefix}:FETCH_RESERVATIONS_LIST_FAILURE`,
  FETCH_RESERVATIONS_LIST_REQUEST: `${typePrefix}:FETCH_RESERVATIONS_LIST_REQUEST`,
};
